import { IActionModel, ISettingsModel } from "../models";
import { Constants } from "../constants/Constants";
import {
    IUtilityFunctionConfig,
    UtilityActionsService,
    utilityActionsService,
} from "./UtilityActionsService";

/** Prefix for per-source cache entries. */
const CACHE_PREFIX = 'predefinedActionsCache';
/** Legacy single-source cache keys, cleared when the whole cache is dropped. */
const LEGACY_CACHE_KEY = 'predefinedActionsCache';
const LEGACY_TIMESTAMP_KEY = 'predefinedActionsCacheTimestamp';
/** Cache for the default catalog loaded from the upstream GitHub folder. */
const DEFAULT_CACHE_KEY = 'defaultPredefinedActionsCache';
const DEFAULT_CACHE_TIMESTAMP_KEY = 'defaultPredefinedActionsCacheTimestamp';
const RATE_LIMIT_STATE_KEY = 'gitHubRateLimitState';
const RATE_LIMIT_RESET_TIME_KEY = 'gitHubRateLimitResetTime';
/** Category assigned to actions from a custom URL that do not declare one. */
const CUSTOM_CATEGORY = 'Custom';

interface IGitHubFile {
    name: string;
    type: string;
    sha?: string;
    size?: number;
    url?: string;
    html_url?: string;
    git_url?: string;
    download_url?: string;
}

export class PredefinedActionsService {
    private CACHE_DURATION_MS = 60 * 60 * 1000; // 1 hour
    private RATE_LIMIT_CACHE_DURATION_MS = 24 * 60 * 60 * 1000; // 24 hours (when rate limited)

    constructor(private utilityActions: UtilityActionsService = utilityActionsService) {
    }

    /**
     * Fetch remote predefined actions for a single URL.
     * Falls back to the cached copy (expired or not) when the fetch fails, so a
     * flaky network never empties the list.
     */
    public async fetchPredefinedActions(url: string): Promise<IActionModel[]> {
        if (!url || url.trim() === '') {
            return [];
        }

        try {
            const cachedData = await this.getCachedActions(url);
            if (cachedData) {
                return cachedData;
            }

            const response = await fetch(url);
            if (!response.ok) {
                throw new Error(`Failed to fetch: ${response.status} ${response.statusText}`);
            }

            const data = await response.json();

            if (!Array.isArray(data)) {
                throw new Error('Invalid JSON structure: expected array of actions');
            }

            if (data.length === 0) {
                return [];
            }

            const normalizedData = this.normalizeActions(data, CUSTOM_CATEGORY);
            await this.cacheActions(url, normalizedData);
            return normalizedData;
        } catch (error) {
            console.error('Error fetching predefined actions:', error);
            const cachedData = await this.getCachedActionsIgnoreExpiry(url);
            return cachedData || [];
        }
    }

    public async refreshPredefinedActions(url: string): Promise<IActionModel[]> {
        await this.clearCache(url);
        return await this.fetchPredefinedActions(url);
    }

    /**
     * The full predefined list shown in the UI: the bundled utility pack (with
     * the user's function config applied), the default catalog from the
     * upstream GitHub folder, then any custom remote sources. Duplicate ids keep
     * their first occurrence.
     *
     * Remote sources are fetched concurrently; one failing source does not stop
     * the others, and the bundled pack is always available offline.
     */
    public async getAllActions(settings: ISettingsModel): Promise<IActionModel[]> {
        const actions: IActionModel[] = [];

        if (settings.showUtilityActions !== false) {
            actions.push(...this.getUtilityActions(settings));
        }

        if (settings.showPredefinedActions !== false) {
            const urls = this.parseUrls(settings.predefinedActionsUrl);
            const [defaults, ...results] = await Promise.all([
                settings.loadDefaultPredefinedActions !== false
                    ? this.fetchDefaultPredefinedActions()
                    : Promise.resolve([] as IActionModel[]),
                ...urls.map(url => this.fetchPredefinedActions(url)),
            ]);
            actions.push(...defaults);
            // Remote packs may carry {{functionBaseUrl}}/{{functionKey}} placeholders
            // (e.g. recipe packs generated by scripts/extract-flow-presets.js);
            // resolve them against the user's function configuration.
            const config = this.toFunctionConfig(settings);
            for (const result of results) {
                actions.push(...result.map(action => this.utilityActions.applyConfig(action, config)));
            }
        }

        return this.deduplicateActions(actions);
    }

    /** Keep the first occurrence of each action id. */
    public deduplicateActions(actions: IActionModel[]): IActionModel[] {
        const seen = new Set<string>();
        const result: IActionModel[] = [];
        for (const action of actions) {
            if (!seen.has(action.id)) {
                seen.add(action.id);
                result.push(action);
            }
        }
        return result;
    }

    /** Bundled utility pack, resolved against the user's function configuration. */
    public getUtilityActions(settings: ISettingsModel): IActionModel[] {
        const config = this.toFunctionConfig(settings);
        const actions = this.utilityActions.getActions(config);

        if (settings.showUtilityParseJsonActions) {
            actions.push(...this.utilityActions.getParseJsonActions(config));
        }

        return this.normalizeActions(actions);
    }

    /** Map persisted settings onto the shape UtilityActionsService expects. */
    public toFunctionConfig(settings: ISettingsModel): IUtilityFunctionConfig {
        return {
            baseUrl: settings.utilityFunctionBaseUrl,
            key: settings.utilityFunctionKey,
            keyMode: settings.utilityFunctionKeyMode,
            baseUrlParameterName: settings.utilityFunctionBaseUrlParameterName,
            keyParameterName: settings.utilityFunctionKeyParameterName,
            includeUnsafe: settings.includeUnsafeUtilityActions,
        };
    }

    /** Refresh every remote source, then rebuild the full list. */
    public async refreshAll(settings: ISettingsModel): Promise<IActionModel[]> {
        const urls = this.parseUrls(settings.predefinedActionsUrl);
        await Promise.all(urls.map(url => this.clearCache(url)));
        await this.clearDefaultCache();
        return this.getAllActions(settings);
    }

    /** Distinct categories present in a list, in first-seen order. */
    public getCategories(actions: IActionModel[]): string[] {
        const categories: string[] = [];
        for (const action of actions) {
            const category = action.category;
            if (category && categories.indexOf(category) === -1) {
                categories.push(category);
            }
        }
        return categories;
    }

    /** Split the setting's newline/comma separated URL list. */
    public parseUrls(value?: string): string[] {
        if (!value) { return []; }
        return value
            .split(/[\n,]/)
            .map(url => url.trim())
            .filter(url => url.length > 0);
    }

    private normalizeActions(actions: IActionModel[], defaultCategory?: string): IActionModel[] {
        return actions.map(action => ({
            ...action,
            isFavorite: false,
            isSelected: false,
            category: action.category ?? defaultCategory
        }));
    }

    /**
     * Cache key derived from the URL so multiple sources cannot overwrite each
     * other. The previous scheme used one global key for every source.
     */
    private cacheKeyFor(url: string): string {
        return `${CACHE_PREFIX}:${this.hash(url)}`;
    }

    private timestampKeyFor(url: string): string {
        return `${CACHE_PREFIX}:${this.hash(url)}:timestamp`;
    }

    private hash(value: string): string {
        let hash = 5381;
        for (let i = 0; i < value.length; i++) {
            hash = ((hash << 5) + hash + value.charCodeAt(i)) | 0;
        }
        return (hash >>> 0).toString(36);
    }

    private async getCachedActions(url: string): Promise<IActionModel[] | null> {
        try {
            const cacheKey = this.cacheKeyFor(url);
            const timestampKey = this.timestampKeyFor(url);
            const result = await chrome.storage.local.get([cacheKey, timestampKey]);
            const cachedActions = result[cacheKey];
            const timestamp = result[timestampKey];

            if (!cachedActions || !timestamp) {
                return null;
            }

            const now = Date.now();
            if (now - timestamp > this.CACHE_DURATION_MS) {
                return null;
            }

            return cachedActions;
        } catch (error) {
            console.error('Error reading cache:', error);
            return null;
        }
    }

    private async getCachedActionsIgnoreExpiry(url: string): Promise<IActionModel[] | null> {
        try {
            const cacheKey = this.cacheKeyFor(url);
            const result = await chrome.storage.local.get([cacheKey]);
            return result[cacheKey] || null;
        } catch (error) {
            console.error('Error reading cache:', error);
            return null;
        }
    }

    private async cacheActions(url: string, actions: IActionModel[]): Promise<void> {
        try {
            await chrome.storage.local.set({
                [this.cacheKeyFor(url)]: actions,
                [this.timestampKeyFor(url)]: Date.now()
            });
        } catch (error) {
            console.error('Error caching actions:', error);
        }
    }

    /** Clear one source's cache, or every source's when no URL is given. */
    public async clearCache(url?: string): Promise<void> {
        try {
            if (url) {
                await chrome.storage.local.remove([this.cacheKeyFor(url), this.timestampKeyFor(url)]);
                return;
            }

            const all = await chrome.storage.local.get(null);
            const keys = Object.keys(all).filter(key => key.indexOf(CACHE_PREFIX) === 0);
            if (keys.length > 0) {
                await chrome.storage.local.remove(keys);
            }
            await chrome.storage.local.remove([
                LEGACY_CACHE_KEY,
                LEGACY_TIMESTAMP_KEY,
                DEFAULT_CACHE_KEY,
                DEFAULT_CACHE_TIMESTAMP_KEY,
            ]);
        } catch (error) {
            console.error('Error clearing cache:', error);
        }
    }

    /** Drop the cached default catalog so the next load re-lists the GitHub folder. */
    public async clearDefaultCache(): Promise<void> {
        try {
            await chrome.storage.local.remove([DEFAULT_CACHE_KEY, DEFAULT_CACHE_TIMESTAMP_KEY]);
        } catch (error) {
            console.error('Error clearing default cache:', error);
        }
    }


    /**
     * Default catalog: every *.json file in the upstream repository's
     * predefined-actions/ folder, listed through the GitHub contents API and
     * fetched raw. The file name becomes the category. Cached for an hour; a
     * 403 from GitHub backs off for 24 hours and serves the stale cache.
     */
    public async fetchDefaultPredefinedActions(): Promise<IActionModel[]> {
        try {
            const isRateLimited = await this.isGitHubRateLimited();
            if (isRateLimited) {
                console.warn('GitHub API rate limit detected. Using cached data.');
                const cachedData = await this.getCachedDefaultActionsIgnoreExpiry();
                return cachedData || [];
            }

            const cachedData = await this.getCachedDefaultActions();
            if (cachedData) {
                return cachedData;
            }

            let allActions: IActionModel[] = [];
            const listResponse = await fetch(Constants.PredefinedActionsGitHubApiUrl);
            
            if (!listResponse.ok) {
                if (listResponse.status === 403) {
                    console.error('GitHub API rate limit exceeded (403 Forbidden)');
                    await this.setGitHubRateLimited();
                } else {
                    console.error(`Failed to fetch file list from GitHub: ${listResponse.status}`);
                }
                const cachedDataIgnoreExpiry = await this.getCachedDefaultActionsIgnoreExpiry();
                return cachedDataIgnoreExpiry || [];
            }

            const fileList = await listResponse.json();
            const jsonFiles = fileList
                .filter((file: IGitHubFile) => file.name.endsWith('.json') && file.type === 'file')
                .map((file: IGitHubFile) => file.name);

            // Fetch all files concurrently using Promise.all for better performance
            const fetchPromises = jsonFiles.map(async (fileName: string) => {
                try {
                    const url = `${Constants.PredefinedActionsBaseUrl}/${fileName}`;
                    const response = await fetch(url);
                    if (!response.ok) {
                        if (response.status === 403) {
                            console.error('GitHub API rate limit exceeded while fetching file (403 Forbidden)');
                            await this.setGitHubRateLimited();
                        } else {
                            console.error(`Failed to load ${fileName} from GitHub: ${response.status}`);
                        }
                        return [];
                    }

                    const data = await response.json();
                    if (Array.isArray(data) && data.length > 0) {
                        const category = fileName.replace(/\.json$/i, '');
                        return this.normalizeActions(data, category);
                    }
                    return [];
                } catch (error) {
                    console.error(`Error loading ${fileName} from GitHub:`, error);
                    return [];
                }
            });

            const results = await Promise.all(fetchPromises);
            allActions = results.flat();

            if (allActions.length > 0) {
                await this.cacheDefaultActions(allActions);
            }
            return allActions;
        } catch (error) {
            console.error('Error fetching default predefined actions:', error);
            const cachedData = await this.getCachedDefaultActionsIgnoreExpiry();
            return cachedData || [];
        }
    }

    private async getCachedDefaultActions(): Promise<IActionModel[] | null> {
        try {
            const result = await chrome.storage.local.get([
                DEFAULT_CACHE_KEY,
                DEFAULT_CACHE_TIMESTAMP_KEY
            ]);
            const cachedActions = result[DEFAULT_CACHE_KEY];
            const timestamp = result[DEFAULT_CACHE_TIMESTAMP_KEY];

            if (!cachedActions || !timestamp) {
                return null;
            }

            const now = Date.now();
            if (now - timestamp > this.CACHE_DURATION_MS) {
                return null;
            }

            return cachedActions;
        } catch (error) {
            console.error('Error reading default cache:', error);
            return null;
        }
    }

    private async getCachedDefaultActionsIgnoreExpiry(): Promise<IActionModel[] | null> {
        try {
            const result = await chrome.storage.local.get([DEFAULT_CACHE_KEY]);
            return result[DEFAULT_CACHE_KEY] || null;
        } catch (error) {
            console.error('Error reading default cache:', error);
            return null;
        }
    }

    private async cacheDefaultActions(actions: IActionModel[]): Promise<void> {
        try {
            await chrome.storage.local.set({
                [DEFAULT_CACHE_KEY]: actions,
                [DEFAULT_CACHE_TIMESTAMP_KEY]: Date.now()
            });
        } catch (error) {
            console.error('Error caching default actions:', error);
        }
    }

    private async isGitHubRateLimited(): Promise<boolean> {
        try {
            const result = await chrome.storage.local.get([RATE_LIMIT_RESET_TIME_KEY]);
            const resetTime = result[RATE_LIMIT_RESET_TIME_KEY];

            if (!resetTime) {
                return false;
            }

            const now = Date.now();
            if (now >= resetTime) {
                await chrome.storage.local.remove([RATE_LIMIT_STATE_KEY, RATE_LIMIT_RESET_TIME_KEY]);
                return false;
            }

            return true;
        } catch (error) {
            console.error('Error checking rate limit state:', error);
            return false;
        }
    }

    private async setGitHubRateLimited(): Promise<void> {
        try {
            const resetTime = Date.now() + this.RATE_LIMIT_CACHE_DURATION_MS;
            await chrome.storage.local.set({
                [RATE_LIMIT_STATE_KEY]: true,
                [RATE_LIMIT_RESET_TIME_KEY]: resetTime
            });
            console.warn(`GitHub rate limit set. Will retry after ${new Date(resetTime).toLocaleString()}`);
        } catch (error) {
            console.error('Error setting rate limit state:', error);
        }
    }

    public async getGitHubRateLimitStatus(): Promise<{ isRateLimited: boolean; resetTime?: number }> {
        try {
            const result = await chrome.storage.local.get([RATE_LIMIT_STATE_KEY, RATE_LIMIT_RESET_TIME_KEY]);
            const isRateLimited = result[RATE_LIMIT_STATE_KEY] === true;
            const resetTime = result[RATE_LIMIT_RESET_TIME_KEY];

            if (!isRateLimited || !resetTime) {
                return { isRateLimited: false };
            }

            const now = Date.now();
            if (now >= resetTime) {
                await chrome.storage.local.remove([RATE_LIMIT_STATE_KEY, RATE_LIMIT_RESET_TIME_KEY]);
                return { isRateLimited: false };
            }

            return { isRateLimited: true, resetTime };
        } catch (error) {
            console.error('Error getting rate limit status:', error);
            return { isRateLimited: false };
        }
    }
}
