// Generated by scripts/pa-popup/gen-icons.mjs - registers only the Fluent MDL2
// icons the popup and side panel render (ours plus those Fluent components use
// internally), instead of initializeIcons()' full glyph map. Add a name to the
// generator and re-run it when a new icon is needed; an unregistered icon shows
// as blank and logs "The icon ... was used but not registered".
import { registerIcons } from '@fluentui/style-utilities';
import { FLUENT_CDN_BASE_URL } from '@fluentui/style-utilities';

const BASE_URL = `${FLUENT_CDN_BASE_URL}/assets/icons/`;
const style = {
  MozOsxFontSmoothing: 'grayscale',
  WebkitFontSmoothing: 'antialiased',
  fontStyle: 'normal',
  fontWeight: 'normal',
  speak: 'none',
} as const;

const SUBSETS: { fontFamily: string; file: string; icons: Record<string, string> }[] = [
  {
    fontFamily: '"FabricMDL2Icons-0"',
    file: 'fabric-icons-0-467ee27f.woff',
    icons: {
      Back: '\uE72B',
      Refresh: '\uE72C',
      Save: '\uE74E',
    },
  },
  {
    fontFamily: '"FabricMDL2Icons-1"',
    file: 'fabric-icons-1-4d521695.woff',
    icons: {
      Error: '\uE783',
      RedEye: '\uE7B3',
      Warning: '\uE7BA',
    },
  },
  {
    fontFamily: '"FabricMDL2Icons-10"',
    file: 'fabric-icons-10-c4ded8e4.woff',
    icons: {
      BulletedList2: '\uF2C7',
    },
  },
  {
    fontFamily: '"FabricMDL2Icons-11"',
    file: 'fabric-icons-11-2a8393d6.woff',
    icons: {
      CircleStopSolid: '\uF2DB',
      VariableGroup: '\uF31B',
    },
  },
  {
    fontFamily: '"FabricMDL2Icons-13"',
    file: 'fabric-icons-13-c3989a02.woff',
    icons: {
      EditSolid12: '\uF4B5',
    },
  },
  {
    fontFamily: '"FabricMDL2Icons-15"',
    file: 'fabric-icons-15-3807251b.woff',
    icons: {
      PasteAsCode: '\uF5D6',
    },
  },
  {
    fontFamily: '"FabricMDL2Icons-2"',
    file: 'fabric-icons-2-63c99abf.woff',
    icons: {
      ChevronUpSmall: '\uE96D',
      Code: '\uE943',
      Completed: '\uE930',
      Copy: '\uE8C8',
      Library: '\uE8F1',
      LightningBolt: '\uE945',
    },
  },
  {
    fontFamily: '"FabricMDL2Icons-3"',
    file: 'fabric-icons-3-089e217a.woff',
    icons: {
      ChevronDownSmall: '\uE96E',
      ClearNight: '\uE9C2',
      ErrorBadge: '\uEA39',
      Record2: '\uEA3F',
      Sunny: '\uE9BD',
    },
  },
  {
    fontFamily: '"FabricMDL2Icons-4"',
    file: 'fabric-icons-4-a656cc0a.woff',
    icons: {
      Broom: '\uEA99',
    },
  },
  {
    fontFamily: '"FabricMDL2Icons-5"',
    file: 'fabric-icons-5-f95ba260.woff',
    icons: {
      Blocked2: '\uECE4',
      Hide: '\uED1A',
    },
  },
  {
    fontFamily: '"FabricMDL2Icons-6"',
    file: 'fabric-icons-6-ef6fd590.woff',
    icons: {
      DoubleChevronUp: '\uEDBD',
    },
  },
  {
    fontFamily: '"FabricMDL2Icons-7"',
    file: 'fabric-icons-7-2b97bb99.woff',
    icons: {
      DoubleChevronDown: '\uEE04',
      SingleBookmark: '\uEDFF',
    },
  },
  {
    fontFamily: '"FabricMDL2Icons-8"',
    file: 'fabric-icons-8-6fdf1528.woff',
    icons: {
      SearchIssue: '\uF09A',
      SetAction: '\uF071',
    },
  },
  {
    fontFamily: '"FabricMDL2Icons"',
    file: 'fabric-icons-a13498cf.woff',
    icons: {
      Add: '\uE710',
      Cancel: '\uE711',
      CheckMark: '\uE73E',
      ChevronDown: '\uE70D',
      ChevronRight: '\uE76C',
      Clear: '\uE894',
      Delete: '\uE74D',
      Download: '\uE896',
      Edit: '\uE70F',
      FavoriteStar: '\uE734',
      FavoriteStarFill: '\uE735',
      Info: '\uE946',
      More: '\uE712',
      Search: '\uE721',
      Settings: '\uE713',
      Undo: '\uE7A7',
      Upload: '\uE898',
    },
  },
];

export const POPUP_ICON_NAMES = SUBSETS.flatMap(subset => Object.keys(subset.icons));

let registered = false;

export function registerPopupIcons(baseUrl: string = BASE_URL) {
  if (registered) { return; }
  registered = true;
  for (const subset of SUBSETS) {
    registerIcons({
      style,
      fontFace: {
        fontFamily: subset.fontFamily,
        src: `url('${baseUrl}${subset.file}') format('woff')`,
      },
      icons: subset.icons,
    });
  }
}
